version: 2
jobs:
  build-and-test:
    docker:
    - image: svyatoslavik/nodechrome:10.13.0-alpine
    steps:
    - checkout
    - restore_cache:
        keys:
        - node-deps-v1-{{ .Branch }}-{{ checksum "package.json" }}
        - node-deps-v1-{{ .Branch }}
        - node-deps-v1
    - run:
        command: npm install
    - run:
        command: npm run test  -- --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
    - save_cache:
        key: node-deps-v1-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/project/node_modules
workflows:
  build-and-test:
    jobs:
    - build-and-test
  version: 2
